# Generated by Django 4.1.4 on 2022-12-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_allTables'),
    ]

    operations = [
    ]
